server: 
  port: 9004

spring:
  profiles:
    active: ${deploy.type}
  application:
    name: myfirst-actuator-admin

#springboot-admin采用集成eureka的方式,来监控注册到eureka中的应用
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      # 将该service注册到集群eureka中
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myfirst-actuator-admin   # 在eureka中显示对应的服务名字
    prefer-ip-address: true     #在eureka中下边的访问路径可以显示IP地址

#取消admin的权限校验
management:
  security:
    enabled: false

logging:
  config: classpath:logback-spring.xml

info:
  version: @project.version@

