server: 
  port: 4002

spring:
  profiles:
    active: ${deploy.type}
  application:
    name: myfirst-config-bus

  rabbitmq:
    host: 127.0.0.1   #生产为公网地址
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/javajing/springcloud-first-config.git
          search-paths: /**
      label: master

#SpringCloud暴露接口，暴露/bus/refresh接口
management:
  security:
    enabled: false

#开启基本的权限，默认为true
security:
  basic:
    enabled: false

logging:
  config: classpath:logback-spring.xml