server: 
  port: 9005

spring:
  profiles:
    active: ${deploy.type}
  application:
    name: myfirst-hystrix-turbine

logging:
  config: classpath:logback-spring.xml

turbine:
  app-config: myfirst-hystrix-dashboard   #要监控的服务的应用名,多个用逗号隔开
  cluster-name-expression: new String("default")   #默认集群名称为“default”

#告诉Turbine Eureka服务器的位置，
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      # 将该service注册到集群eureka中
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myfirst-hystrix-turbine   # 在eureka中显示对应的服务名字
    prefer-ip-address: true     #在eureka中下边的访问路径可以显示IP地址